spring.application.name=aqicn
server.port=8085
aqicn.token=cfe036ba049029c77cb6926a1d632a1350836492
aqicn.baseurl=http://api.waqi.info/feed/


cors.allowed-origins=*
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*
cors.exposed-headers=*


# https://api.waqi.info/feed/mumbai/?token=cfe036ba049029c77cb6926a1d632a1350836492